### ISSUE TITLE
Improve grammar

### ISSUE THREAD

**Issue by FranckCo** [InseeFr/VTL-Tools#11]
Problems identified so far:

- [ ] Unary operator is redondant
- [ ] Precedence of PLUS versus MINUS
- [ ] Some rules do not use named elements (e.g. SUBSTR could use 'leftExpression', etc.)
- [ ] Some functions can have an infinite number of parameters (e.g. SUBSTR)

**Comment by hadrienk** [comment]
Merge the italian grammar first

**Comment by FranckCo** [comment]
Problems fixed with new version of the grammar (https://github.com/InseeFr/VTL-Tools/tree/master/vtl-sources/Vtl-3.0-Istat), except the fourth item, which has been transformed into a specific issue (#39).
