### ISSUE TITLE
Unary

### ISSUE THREAD

**Issue by NicoLaval** [InseeFr/VTL-Tools#33]
`+1` is an unary expr
`+ 1` is an unary expr
`-1` is a constant
`- 1` is an unary expr

UnaryExpr is nevertheless defined as weel for negative and positive numbers: 
op=(PLUS|MINUS) right=expr

**Comment by NicoLaval** [comment]
https://groups.google.com/forum/#!topic/antlr-discussion/15-KuOb5Pqg

**Comment by hadrienk** [comment]
Istat did some changes on the INTEGER_CONSTANT token. We should wait/backport to see if it helps.
